sudo: required

services:
  - docker

env:
  - TRAVIS_CI_BUILD=true
  
before_script:
  - chmod +x MyConference/docker/build
  
script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull appertise/oracle-jdk8
  - docker build -t clemenshuebner/amos-ss16-proj8:1.0 .
  - docker push clemenshuebner/amos-ss16-proj8:1.0
